language: python
dist: bionic
python:
  - "3.7"
install:
  - pip install --upgrade pip pipenv
  - pipenv install
  - pipenv install coveralls
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
notifications:
  email: false